<!DOCTYPE html>
<html>
<head>
    <title>Nginx is serving simple PHP</title>
</head>
<body>

    <h1>Welcome!</h1>

    <?php
    echo "<p>This is a paragraph generated by PHP.</p>";

    $name = "wide";
    echo "<p>Armel should be " . $name . "!</p>";
    ?>

    <p>This PHP file is served within the nginx module itself.</p>
    <p>If you see this while developing only the nginx module, great. It is serving.</p>
    <p>If you see this while developing the wordpress module, welp, glhf.</p>

</body>
</html>
